### ISSUE TITLE
[Feature request] Allow other online sources than Google translate

### ISSUE THREAD

**Issue by Nokia808** [dialect-app/dialect#114]
Hi. 

Currently, your cute application allow translation from only one online site, Google translate. But there are other cute source for online translation & it will be very useful to add an option allowing user to select from several choices.

Example for other online translation sources are:
https://www.bing.com/translator/
https://translate.yandex.com/
https://www.translate.com/

Kindly, see which of them could be integrated with your application.

Best.

**Comment by fushinari** [comment]
There are also other open issues regarding implementing alternative backends. And it's planned. It's just that I haven't had the time to implement it, especially because it needs to be thought out well enough for easy future extension. I assume it's a similar story for @rafaelmardojai .

**Comment by rugk** [comment]
I'd also suggest to open one issue per suggested backend.
There already is #47, #112 and https://github.com/gi-lom/dialect/issues/119.

**Comment by rafaelmardojai** [comment]
We already support Yandex and Bing, does https://www.translate.com/ have any benefit over them?
