### ISSUE TITLE
No longer reference Google Translate on the About dialog

### ISSUE THREAD

**Issue by nahuelwexd** [dialect-app/dialect#137]
Since the application now also supports LibreTranslate and no longer just Google Translate, references to the latter in the app description should be removed

https://github.com/gi-lom/dialect/blob/4fbd24923e13cc6983277fb8bf2461b2eeedd119/data/resources/about.ui#L12

(also, in the repo description too)

**Comment by rafaelmardojai** [comment]
I updated the README, AppStream Metadata and .desktop file... but you always forget something 😂.

**Comment by fushinari** [comment]
Ah... The repo description will have to be changed by @gi-lom .

**Comment by Etamuk** [comment]
And what about the translation string in .pot file? :scream_cat: 
( "A translation app for GNOME based on **Google Translate**." )

**Comment by rafaelmardojai** [comment]
> And what about the translation string in .pot file? 

It's the same from `about.ui`.
