### ISSUE TITLE
Update translations for 1.3.0

### ISSUE THREAD

**Issue by fushinari** [dialect-app/dialect#157]
Dialect 1.3.0 is almost ready. As always, we would be grateful if you're able to find time to update the translations. :smile: 

Thank you to all translators who have stuck with us through each release and thank you for allowing users of your specific languages to use the application without having to know a non-native language! I hope you realize that your efforts are recognized and very much appreciated. :smile: 

- [x] German @Etamuk
- [x] Spanish @rafaelmardojai 
- [x] Persian @musicsd
- [x] Hungarian @meskobalazs
- [x] Indonesian @cho2
- [x] Italian @albanobattistella
- [x] Dutch @Vistaus
- [x] Brazilian Portuguese @xfgusta
- [x] Russian @nexeleriot
- [x] Swedish @eson57
- [x] Turkish @v30xy
- [x] Croatian @milotype 
- [x] Czech @pervoj 

We have no set release date, we'll just release when everything is in place. So no need to sweat over it. :smile:

**Comment by pervoj** [comment]
Done #159

**Comment by Vistaus** [comment]
Done! 🙂 #161

**Comment by Etamuk** [comment]
German translation is also done :-)

**Comment by meskobalazs** [comment]
Done at last :)
