### ISSUE TITLE
Allow selection of pronunciation text

### ISSUE THREAD

**Issue by cwmke** [dialect-app/dialect#176]
Title says it all. The new pinyin feature works great for Chinese characters 🚀 but there is no way to select it currently. In my case this is needed in order to build flashcards. I don't think it needs a separate copy button but the ability to select the text and then do a standard ctrl + c would be great.

**Comment by fushinari** [comment]
Text is now selectable, but for some reason, trying to copy using Ctrl-C from the label does not seem to work on my end. For now, copying should work with right click.

**Comment by rafaelmardojai** [comment]
> Text is now selectable, but for some reason, trying to copy using Ctrl-C from the label does not seem to work on my end. For now, copying should work with right click.

Yeah, same for me...
