### ISSUE TITLE
ANNOUNCEMENT: Weblate as our main translation platform

### ISSUE THREAD

**Issue by rafaelmardojai** [dialect-app/dialect#182]
Hey translators! 

We're moving to Weblate as our main translation platform to ease contribution!

We're also going to make the calls to update translations there, so make sure to add Dialect to your watched projects.

You can join here: https://hosted.weblate.org/engage/dialect/.

CC @Etamuk, @musicsd, @yarons, @meskobalazs, @cho2, @albanobattistella, @Vistaus, @JulianoSCbah, @xfgusta,  @nexeleriot, @eson57, @noteqnil, @milotype, @pervoj.

**Comment by fushinari** [comment]
I'm locking Weblate for now because we're making some changes to how the repository is organized, but we'll be back up soon. :smile: Sorry for any inconvenience caused

**Comment by fushinari** [comment]
Weblate should be back up now. Translations have now been moved out to [dialect-app/po](https://github.com/dialect-app/po).

**Comment by pervoj** [comment]
Can we still use file translation method?

**Comment by rafaelmardojai** [comment]
> Can we still use file translation method?

That's what we want if someone wants to, but we're investigating if it causes issues on the Weblate side.

**Comment by pervoj** [comment]
Czech translation for now updated from Weblate, but GTranslator is still more comfortable in my opinion.

**Comment by yarons** [comment]
@pervoj It's pretty easy to download and upload files to Weblate, it's a little less cooperative but it's possible, if you want you can add a script with `wlc` (Weblate CLI Tool) to pull and push the file for you.

**Comment by fushinari** [comment]
> Can we still use file translation method?

@pervoj I've looked into this a bit more and from what I see, it's technically possible to update it from GitHub, unless someone edits it in Weblate at the same time, in which case, it will cause a merge conflict, causing Weblate to lock the repository and wait for us (repository owners) to fix the merge conflict. So it's very risky.

The best solution would be to use the Weblate client `wlc` from either pip or your package repository of choice.

**Comment by fushinari** [comment]
The move to Weblate is now complete :)
