### ISSUE TITLE
Plugin system for translation sources

### ISSUE THREAD

**Issue by walking-octopus** [dialect-app/dialect#185]
What do you think about implementing a simple plugin system for translation sources? Each translation source is already a separate module, so why not make this system more extendable and load them from `~/.config/Dialect/plugins`?

**Comment by fushinari** [comment]
Sorry but this feature would mean allowing execution of code from the home directory, which is a security risk. As such, we can't implement this feature.

If you'd like to, you can send a pull request with a new translator and we'd be glad to review and accept it. That would allow everyone to use the new translator in a safe manner.

As you mentioned, adding a translator is now as easy as adding the required module. You can even copy one of the existing modules and base your work on it.

Testing it is easy enough through either GNOME Builder or through [local builds](https://github.com/dialect-app/dialect#building-from-git). And if you need any help along the way, you can open an issue here and we'd be happy to assist. :)

Hope you understand :sweat_smile:
