### ISSUE TITLE
Error in audio transcription

### ISSUE THREAD

**Issue by wsalmeida** [dialect-app/dialect#186]
Hi I have an error in the audio transcripts in version 1.3.0 of the application which I believe is a bug I am using in debian with xfce.
https://imgur.com/xo7DDzU.png

**Comment by fushinari** [comment]
It works fine for me.

Please provide additional information like the version of gTTS that you have installed and other dependencies since you don't seem to be running the flatpak (which is the recommended mode of installation).

**Comment by wsalmeida** [comment]
I did the installation with debian package manager so he took charge of downloading the application and its dependencies now if this is a bug and is a problem with dependencies ideally it would report to the project maintainer in the debian distribution.

**Comment by fushinari** [comment]
It may be because python-gtts is at 2.0.3 on the debian sid repos. I suggest you report the same to the debian package maintainer since it's a packaging issue rather than a bug on our end.

**Comment by wsalmeida** [comment]
Okay so I'll close here and do what I suggested.
