### ISSUE TITLE
Failed to choose LibreTraslate as Translator.

### ISSUE THREAD

**Issue by CleoMenezes** [dialect-app/dialect#190]
![image](https://user-images.githubusercontent.com/54215258/129431076-6108df2a-bc01-4703-ab1d-40d991cb969d.png)

**How to reproduce the error:**
$ flatpak run com.github.gi_lom.dialect
Gtk-Message: 22:00:09.161: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:00:09.161: Failed to load module "pk-gtk-module"
Error: The read operation timed out

**Comment by fushinari** [comment]
Seems like a network issue?

**Comment by CleoMenezes** [comment]
> Seems like a network issue?

It's not happen with Google translate.

**Comment by LyesSaadi** [comment]
What server are you using?

**Comment by fushinari** [comment]
This doesn't look like our bug. A read operation timeout indicates that you're having trouble reaching the LibreTranslate instance. I've tested with the default instance (translate.astian.org) and it seems to work fine.

**Comment by fushinari** [comment]
@CleoMenezes do you have any kind of additional information you could provide regarding this issue? If not, I will probably be closing this in around a week since we have no other info to go off of.
