### ISSUE TITLE
Does not work behind a socks proxy server 

### ISSUE THREAD

**Issue by bellegarde-c** [dialect-app/dialect#192]
![130969299-c44cefc7-dfb5-426a-93db-5d15de372e8e](https://user-images.githubusercontent.com/57196916/131656201-28d6af41-f27c-471b-91ee-69d8154aed89.png)

**Comment by fushinari** [comment]
Hi,

This definitely seems like something we would want to fix, do you have any easy way I could test and reproduce this?

Btw, thank you for all your work on Lollypop, love it. Looking forward to Lollypop2 :)

**Comment by bellegarde-c** [comment]
GNOME use an unversionned proxy scheme for socks. (all_proxy variable is set by user session based on gsettings)

Is handled as this in Lollypop as Python wants a versionned URI: socks4:// or socks5://

https://gitlab.gnome.org/World/lollypop/-/blob/master/lollypop/utils.py#L176

**Comment by bellegarde-c** [comment]
And to reproduce:

`ssh -D 8080 a_ssh_host`

And this in GNOME settings:
![Capture d’écran du 2021-09-01 13-20-55](https://user-images.githubusercontent.com/57196916/131662856-ceec5305-e23b-403d-9c4e-ae0fc7201b6e.png)

**Comment by fushinari** [comment]
Only partially fixed.

**Comment by fushinari** [comment]
#235 , #236 and #243 should have fixed this.
