### ISSUE TITLE
Please allow languages to be translatable

### ISSUE THREAD

**Issue by ovari** [dialect-app/dialect#193]
Please allow the languages in the drop-downs to be translatable. Please see image below.

![kép](https://user-images.githubusercontent.com/17465872/132141208-698cd153-5ac9-4d2e-8eb1-fe76c33d3c07.png)

What do you think?

Thank you

**Comment by rafaelmardojai** [comment]
Those languages come from the `py-googletrans` library, we could copy that list and make it translatable, but would be a lot of work for translators :P. 

But I'm open to the change, @fushinari what do you think?

**Comment by ovari** [comment]
Thank you for being open to the improvement (or as you say `change`).

Strange, when translating using translate.google.com it shows in the Hungarian language.

![kép](https://user-images.githubusercontent.com/17465872/132141673-f3776253-e70e-45bb-938e-24b877085fe8.png)

It is not that much work as the languages are shown for each languages by using `hl=<locale>`. For Hungarian, add `hl=hu`. Other examples are:
1. https://translate.google.com/?sl=hu&tl=en&op=translate&hl=es
2. https://translate.google.com/?sl=hu&tl=en&op=translate&hl=de

Hope this helps.

Please enable the languages to also show in the language of the operating system even if `LibreTranslate` is used.

Thank you once again.

**Comment by rafaelmardojai** [comment]
Yeah, probably trying to get the langs names from `translate.google.com` would be smarter.

About LibreTranslate, I don't think users using it will want to make requests to Google servers. Maybe we can automate the translation files creation in some way using Google.

**Comment by ovari** [comment]
It can be done manually if you can't automate the translation file creation as it only has to be done once.

**Comment by rafaelmardojai** [comment]
> It can be done manually if you can't automate the translation file creation as it only has to be done once.

Yep, but some tool to get all the languages names from all languages available on Google would be cool.

**Comment by fushinari** [comment]
> what do you think?

It's possible and would definitely be an improvement. :)

> Yep, but some tool to get all the languages names from all languages available on Google would be cool.

I see what you mean, for reducing work for translators right? Might be as simple as writing a script, let's see.

**Comment by milotype** [comment]
I'd suggest to look at [ISO-codes project at Weblate](https://hosted.weblate.org/projects/iso-codes/#components). Maybe you can use those translations.
- ISO 639-2 and ISO 639-3 for languages
- ISO 4217 for currencies

Find some explanation further down on the page at https://salsa.debian.org/iso-codes-team/iso-codes

I don’t know how to do it, I’m not a programmer … but maybe this info helps.

**Comment by ovari** [comment]
Thank you
