### ISSUE TITLE
Enable translation submission to LibreTranslate

### ISSUE THREAD

**Issue by ovari** [dialect-app/dialect#194]
Would be great if the UI could be improved to enable translation submissions to LibreTranslate.

Please see https://github.com/argosopentech/argos-translate/discussions/61.

What do you think?

Thank you

cf. https://github.com/LibreTranslate/LibreTranslate/issues/130

**Comment by fushinari** [comment]
Implementation of this in Dialect would normally depend on its implementation in LibreTranslate since we use LibreTranslate rather than Argos directly. Or are you suggesting Dialect have an implementation independent of LibreTranslate?

**Comment by ovari** [comment]
> Or are you suggesting Dialect have an implementation independent of LibreTranslate?

No.

Perhaps a 3-way conversation with the developers of Dialect, LibreTranslate and Argos is required?

It seems that the ideal solution would be for LibreTranslate.org to allow suggestions which would populate Argos directly. This could be implemented in Dialect without reinventing the wheel. That way suggestions can be received via LibreTranslate and Dialect.

Hopefully this will allow code reuse and fixing any bugs would fix them across all programs.

Thank you once again.

**Comment by fushinari** [comment]
Yep, in that case, it should be fine. We plan to implement any translation-related features accessible through the LibreTranslate API.

**Comment by fushinari** [comment]
Technically, this is done. But there are no public LibreTranslate instances anymore that have suggestions without API keys being required.

That would mean API keys come first. Unfortunately, I'm having trouble setting up a local instance due to network troubles and I don't have an API key for the official instance (libretranslate.com), making it impossible to test any further.

**Comment by fushinari** [comment]
#235 fixed this.
