### ISSUE TITLE
Hungarian translations with LibreTranslate

### ISSUE THREAD

**Issue by ovari** [dialect-app/dialect#196]
Hungarian shows as a language option at https://libretranslate.com/.

Can Hungarian please show as a language option in Dialect when LibreTranslate is used?

Thank you

**Comment by rafaelmardojai** [comment]
Dialect's libretranslate backend gets the languages dynamically from the server, but remember that the default provider is `translate.astian.org` because it's more stable.

**Comment by ovari** [comment]
Do you know if `translate.astian.org` automatically updates? Thank you

**Comment by rafaelmardojai** [comment]
Can't say right now, but you can change the server on settings.

**Comment by ovari** [comment]
Thinking of other people, it would be great if it just works (without changing server settings); hence, does `translate.astian.org` have a GitHub repository or someway to contact them directly? Thank you once again.

**Comment by rafaelmardojai** [comment]
@fushinari do you remember why we chose astian over libretranslate.com? I think libretranslate.com was running an alpha version or something like that?

**Comment by fushinari** [comment]
The developer of LibreTranslate specifically asked us not to use that instance as our default.

**Comment by ovari** [comment]
Hungarian (and Finnish) are now showing. Thank you very much!
