### ISSUE TITLE
The app is called “Dialect” but it doesn’t support dialects lmao

### ISSUE THREAD

**Issue by fitojb** [dialect-app/dialect#198]
I just think it’s a bit ironic that I can’t e.g. translate to Brazilian or European or Angolan Portuguese, accounting for the vocabulary and grammar differences in each ;-)

**Comment by rafaelmardojai** [comment]
So the point of opening the issue is?
Do you want to suggest a name change? Or request the creation of translation models for different language dialects in LibreTranslate?

Maybe we need to create some chat room to avoid this kind of issue tickets ;-)

**Comment by fitojb** [comment]
Sure, feel free to move this to a GitHub Discussion instead. :+1: 

Sorry for being unclear. I think the name could use some improvement, certainly. It’s not great to suggest that the app does something that it’s currently out of reach for most machine translation systems, so something less misleading would be very helpful. And I don’t know much about LibreTranslate, but if it can avoid duplicating work by inheriting some linguistic rule logic from e.g. Apertium and LanguageTool, that’d be great.

**Comment by rafaelmardojai** [comment]
If you want to know how we ended up with "Dialect" you can check this issue: #29.

I really don't think that "Dialect" is misleading, from my perspective it says nothing, it's just a pretty name related to linguistics. You need to read the description to understand what it does: `Translate between languages` / `A translation app for GNOME`. 

More than out of reach, I would say that is unnecessary, most people can understand what is said in their dialect's mother language, more useful is translating from a dialect to a complete different language and Google for example already supports that.

Apertium is rule-based while LibreTranslate (which is a web API wrapping Argos Translate) uses neural machine translation, but I guess some work can be can be recycled.
