### ISSUE TITLE
Translate selected text with shortcut

### ISSUE THREAD

**Issue by Alexios13** [dialect-app/dialect#207]
Is it ease to add a shortcut that open dialect and translate the selected text? 
Crow-translate has this future and it's very helpful. I select a text with my cursor, I press Ctrl + Alt + E and the crow-translate open with the text already translated. So there will be no need to copy and paste the text each time to the dialect.

![2021-09-28_17-18](https://user-images.githubusercontent.com/91549003/135105754-5779b956-5c8c-40d4-afc4-a3da0df85d5b.png)

**Comment by fushinari** [comment]
A proper implementation for this is impossible from our side in Wayland. You could, however, make use of Dialect's "-t" commandline parameter to create your own script and link a shortcut to it.

**Comment by Alexios13** [comment]
I didn't know that this is not possible on Weyland. Thank you!

**Comment by fushinari** [comment]
You're welcome :)

Like I said, though, as far as a user is concerned, it's still possible. You just need to setup a command to launch Dialect with the primary clipboard content passed in "-t". A tool you can use for that is [wl-clipboard](https://github.com/bugaevc/wl-clipboard). The command could be like:
```bash
dialect -t "$(wl-paste -p)"
```

It should work.
