### ISSUE TITLE
`Preferences` in the titlebar is untranslated

### ISSUE THREAD

**Issue by ovari** [dialect-app/dialect#215]
`Preferences` in the titlebar is untranslated as shown in the image below

![kép](https://user-images.githubusercontent.com/17465872/137863372-db79fff0-2b16-4e96-9cc5-5dcadb271020.png)

Thank you

**Comment by ovari** [comment]
Hope this is an easy fix as `Keyboard Shortcuts` in the titlebar are translated as shown in the image below

![kép](https://user-images.githubusercontent.com/17465872/137863682-80f82855-1e51-4d9c-9edb-2f943cc3ca0f.png)

Thank you

**Comment by fushinari** [comment]
Can you confirm if this is still a bug?

**Comment by ovari** [comment]
Closing as fixed. Thank you

![Preferences window](https://user-images.githubusercontent.com/17465872/179427182-61dc7cbc-a689-4cdc-bf88-edab4a46d68a.png)
