### ISSUE TITLE
Building from release archive, meson error

### ISSUE THREAD

**Issue by BlueManCZ** [dialect-app/dialect#220]
I'm trying to build dialect from the source and I'm using the official release [1.4.1.tar.gz](https://github.com/dialect-app/dialect/archive/refs/tags/1.4.1.tar.gz) archive. But when I run `meson builddir --prefix=/usr/local`, I get an error:

```
meson.build:38:0: ERROR: Non-existent build file 'po/meson.build'
```

**Comment by LyesSaadi** [comment]
You need to install the translation files from the same release into the `po/` folder before :
https://github.com/dialect-app/po

**Comment by BlueManCZ** [comment]
Thank you, that solved it.
