### ISSUE TITLE
Translating with googletrans-3.0.0 not working

### ISSUE THREAD

**Issue by BlueManCZ** [dialect-app/dialect#221]
All I'm getting is
```
Translation has failed
```

I installed the [googletrans](https://pypi.org/project/googletrans/#files) dependency from pypi, but there is only version 3.0.0. I noticed the thread https://github.com/dialect-app/dialect/issues/133 where you talked about it. My question is which version of the library is currently officially supported and where can I find it?

**Comment by rafaelmardojai** [comment]
You need `googletrans==3.1.0a0`

**Comment by fushinari** [comment]
Two versions are currently supported: 3.1.0a0 and the current state of the [`feature/rpc`](https://github.com/ssut/py-googletrans/commit/0255662360fc579b4dba2893e931905aedaf9ef0) branch of googletrans.
