### ISSUE TITLE
regression: translation backend not working

### ISSUE THREAD

**Issue by harrisonrobin** [dialect-app/dialect#224]
Due to local policy issues, google's main translation services does not work except with a designated endpoint translate.google.cn by google in mainland china.  The application used to work correctly on Fedora for previous releases maybe an upstream change of the api's used by application is causing the translations to fail to fail now.  

version: 1.4.1

**Comment by fushinari** [comment]
There shouldn't be any regression on our end afaik. Are you able to reproduce this with the flatpak?

**Comment by fushinari** [comment]
Marking as stale and closing since there's nothing we can do.
