### ISSUE TITLE
Default LibreTranslate instance does not work

### ISSUE THREAD

**Issue by werdahias** [dialect-app/dialect#229]
I installed the latest dialect app on Debian testing. When I open it I get: 
`Translation service could not be loaded. Name or service unknown.`
Translator is set to LibreTranslate, URL to translate.astian.org.

**Comment by CountOmega** [comment]
yeah flatpak is working. I don't have the same error there.

**Comment by CountOmega** [comment]
I built the deb from source, still got the same issue.

**Comment by fushinari** [comment]
> I built the deb from source, still got the same issue.

@jonassmedegaard could you look into why this is happening? I don't have a debian system I could test on

**Comment by jonassmedegaard** [comment]
I can confirm this issue - on a Debian unstable system using the official Debian packaging of release `1.4.1` with no patches applied.  More detailed (but only slightly more) is the console output:
```
$ LANG=C dialect
Error: [Errno -2] Name or service not known

(com.github.gi_lom.dialect:2743198): Gtk-CRITICAL **: 16:54:07.412: gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
```

If that's not enough clues, then please guide me how to enable more verbose output, if possible, or which environmental details might be helpful that I gather.

**Comment by fushinari** [comment]
Can you give me the output of:
```bash
gsettings list-recursively com.github.gi_lom.dialect
```

**Comment by jonassmedegaard** [comment]
Certainly:
```shell
$ gsettings list-recursively com.github.gi_lom.dialect
com.github.gi_lom.dialect libretranslate-instance ''
com.github.gi_lom.dialect dark-mode false
com.github.gi_lom.dialect google-src-langs @as []
com.github.gi_lom.dialect live-translation false
com.github.gi_lom.dialect backend-name 'libretranslate'
com.github.gi_lom.dialect libretranslate-dest-langs @as []
com.github.gi_lom.dialect libretranslate-src-langs @as []
com.github.gi_lom.dialect backend -1
com.github.gi_lom.dialect translate-accel 0
com.github.gi_lom.dialect google-dest-langs @as []
com.github.gi_lom.dialect window-size [800, 300]
com.github.gi_lom.dialect backend-settings '{"libretranslate": {"src-langs": ["en", "de", "fr", "es"], "dest-langs": ["de", "en", "ru", "zh"]}}'
com.github.gi_lom.dialect show-pronunciation false
com.github.gi_lom.dialect src-auto true
com.github.gi_lom.dialect tts-name ''
```

**Comment by rafaelmardojai** [comment]
Interesting, so libretranslate doesn't have a instance url in its settings.

**Comment by fushinari** [comment]
Try setting instance to `translate.api.skitzen.com`

**Comment by fushinari** [comment]
> Interesting, so libretranslate doesn't have a instance url in its settings.

Seems the Astian instance is down.

**Comment by rafaelmardojai** [comment]
@fushinari shouldn't it have a `instance-url` on its `backend-settings` json?

**Comment by fushinari** [comment]
No. It's hard-coded to default to `translate.astian.org`

**Comment by rafaelmardojai** [comment]
Right, but shouldn't save it to a setting after the first run? (lol I'm forgetting how works our own code)

**Comment by fushinari** [comment]
> Right, but shouldn't save it to a setting after the first run?

Nope, unless the user manually sets a different instance at some point, it will be taken from `libretrans.py`

> lol I'm forgetting how works our own code

Lol I get you, I had to look to make sure too

**Comment by fushinari** [comment]
@jonassmedegaard Try setting "Translator Instance" in Preferences to `translate.api.skitzen.com`

**Comment by jonassmedegaard** [comment]
that works

**Comment by jonassmedegaard** [comment]
I did not file this report, but seems to me the subject is accurate: The **service** is not working.
Perhaps the fix for the app is to communicate more clearly what to do when a service is not working?

**Comment by fushinari** [comment]
Yeah, that makes sense. What's the error message you're getting?

In the next version (2.0), it will look something like this:
![Screenshot from 2021-12-16 23-46-43](https://user-images.githubusercontent.com/28823274/146426695-deefe691-f14c-463f-b8f3-d8050eeba007.png)

Could you show me what the application looks like in the Debian release?

**Comment by jonassmedegaard** [comment]
looks the same.

When I read that error message, I don't feel encouraged to go mess with config options - but perhaps that's just me...

**Comment by jonassmedegaard** [comment]
perhaps if it said something like this I would feel encouraged to go mess in the configurations even if I had never gone there before:
> Failed to connect to "translate.astian.org" (perhaps your configured translation service is down and you need to select another?)

**Comment by rafaelmardojai** [comment]
Maybe for the libretranlate case we can add a subtitle with something like `An error occurred when trying to connect to {instace-url}`.

**Comment by jonassmedegaard** [comment]
Even better if it was then possible to *select* another service - not only edit a text input field where I have no clue what alternative might work - but an error message that was targeted more at a non-technical audience would be a start in my opinion

**Comment by fushinari** [comment]
> Even better if it was then possible to *select* another service - not only edit a text input field where I have no clue what alternative might work - but an error message that was targeted more at a non-technical audience would be a start in my opinion

I really want to do this. But as is obvious from this case, LibreTranslate instances come and go. We can't have a static list of instances. There's also no reliable directory of LibreTranslate instances.

Not to mention, most of them require API keys now. So only a few will work for a regular user anyway. Even if we implement API keys support, it's pretty much pointless for a non-technical user.

**Comment by jonassmedegaard** [comment]
Quoting Mufeed Ali (2021-12-17 05:50:39)
> > Even better if it was then possible to *select* another service - not only edit a text input field where I have no clue what alternative might work - but an error message that was targeted more at a non-technical audience would be a start in my opinion
> 
> I really want to do this. But as is obvious from this case, LibreTranslate instances come and go. We can't have a static list of instances. There's also no reliable directory of LibreTranslate instances.
> 
> Not to mention, most of them require API keys now. So only a few will work for a regular user anyway. Even if we implement API keys support, it's pretty much pointless for a non-technical user.

Maybe then simply link to the list here: https://github.com/LibreTranslate/LibreTranslate#mirrors

**Comment by fushinari** [comment]
The current situation with LibreTranslate isn't great. We really really want the free and open source option to have a reliable yet simple option. We wish it were as simple as having a default free instance with some limits and an optional API key. But there's no such option. So, this kind of issue will be pretty common unfortunately.

**Comment by fushinari** [comment]
An option we're considering is simply not setting a default instance and having an initial setup interface that has a link to https://github.com/LibreTranslate/LibreTranslate#mirrors . Unfortunately though, even that list is out-of-date.

**Comment by Gwerr1002** [comment]
In Dialect go to preferences. If you have libretranslate, on the translate service, go to this link https://github.com/LibreTranslate/LibreTranslate#mirrors and copy any mirror. This should work

**Comment by mufeedali** [comment]
From the next release, we will be using our own instance, which should hopefully resolve such issues.
