### ISSUE TITLE
Gstreamer issue on opensuse

### ISSUE THREAD

**Issue by RDKRACZ** [dialect-app/dialect#230]
Dialect Fedora package requires `gstreamer1-plugins-base` but this package is called `gstreamer-plugins-base` in suse. Yeah it's annoying...

**Comment by fushinari** [comment]
I think that's intended. Fedora RPMs will not necessarily work with openSUSE. What will work is using the OBS with modified rpmspec files suited for openSUSE, which you can base on the spec for Fedora. Hope that answers your question! :)
