### ISSUE TITLE
Crash when choosing LibreTranslator in Flatpak version

### ISSUE THREAD

**Issue by bahtioraliev** [dialect-app/dialect#231]
**Crash when choosing LibreTranslator** 

Version - 1.4.1
Package - flatpack 
Os - PopOs

When you chose the LibreTranslator the app just crash
![image](https://user-images.githubusercontent.com/76793434/148221880-90b5551c-a7e0-4c95-ae3b-d4d7fe488f5f.png)

**Comment by fushinari** [comment]
It's a known bug specific to the Flatpak version. Fixed in `main`, i.e. fixed in the next release.

**Comment by fushinari** [comment]
Closing since fixed in `main`.
