### ISSUE TITLE
RFE - add favorite languages implantation 

### ISSUE THREAD

**Issue by bahtioraliev** [dialect-app/dialect#232]
Add an ability for custom setup of favorite languages 

- For example, add stars marks for languages that you use often
- In addition, add shortcuts to quick (favorite) language switch

**Comment by fushinari** [comment]
I think the recent languages list serves this purpose well enough already. Is there any specific usecase for this?

**Comment by bahtioraliev** [comment]
In regards to "shortcuts to quick (favorite) language switch"
The ctrl+s switch between source translation and target. 
On daily bases, I use 3 different languages and would like to have a shortcut to switch between those languages quickly.

**Comment by jeblad** [comment]
It isn't obvious how a shortcut should work, but what about typing the language code with the alt-key down? Lets say you want to translate from Norwegian (no) and into English (en) and type [Alt][n]+[o] for source language and [Shft][Alt][e]+[n] for destination language? It could work as the alt-key isn't much used in this app.

**Comment by mufeedali** [comment]
Should be more efficient to use the Ctrl+T and Ctrl+S shortcuts and search to pick a language as of now. If the current UI/UX isn't sufficient, please re-open the issue to let us know the same :)
