### ISSUE TITLE
[AUR Package] Error in httpcore module

### ISSUE THREAD

**Issue by cryptolog89** [dialect-app/dialect#234]
I run the program from the terminal in Manjaro and gives an error:

![zer0x@home:~_001](https://user-images.githubusercontent.com/95739837/151375471-eafd47f1-4c45-4db1-823b-75c0908eeeda.png)

**Comment by fushinari** [comment]
Sorry, this looks like an issue with packaging. @yochananmarqos can you have a look?

**Comment by yochananmarqos** [comment]
@fushinari I'm aware, it's been broken for awhile now. No version of `python-googletrans` or `python-httpx` works anymore.

**Comment by fushinari** [comment]
I see. Then I guess that the recommendation for now is to switch to the Flatpak version....

**Comment by fushinari** [comment]
@yochananmarqos Can you try the patch at: https://github.com/ssut/py-googletrans/pull/291 ?

**Comment by yochananmarqos** [comment]
@fushinari Using that patch apparently fixes the error in the OP, however Dialect shows the banner at the top,  _Translation failed. Please check for network issues._

**Comment by fushinari** [comment]
Ah, then I guess this is kind of out of our control for now.

We're working on our fork of py-googletrans (https://github.com/dialect-app/py-googletrans). So hopefully that will fix some of the issues people are having with Google.

**Comment by yochananmarqos** [comment]
I tried your fork, but results in the same error. This is with `python-httpx` 0.22.0-1.

**Comment by fushinari** [comment]
Yes, it's not ready yet. It will be ported over to libsoup once some other stuff is done, which will avoid issues with httpx entirely.

**Comment by LyesSaadi** [comment]
This now affects Fedora 36.

https://bugzilla.redhat.com/show_bug.cgi?id=2070399

**Comment by fushinari** [comment]
It won't effect anyone from the next release onwards :)

**Comment by LyesSaadi** [comment]
Thank you for the push. Do you intend to push a release right away, or should I just push a pre-release version?

**Comment by LyesSaadi** [comment]
Also, the PR seems to have got rid of py-googletrans, could the README.md reflect this?

**Comment by yochananmarqos** [comment]
I've updated the `dialect-git` AUR package, it's working again. Thanks @fushinari! :+1:

**Comment by fushinari** [comment]
> Do you intend to push a release right away, or should I just push a pre-release version?

We want to do some more polishing before an actual release. You can see an incomplete list of issues we're working on here: https://github.com/dialect-app/dialect/wiki/GTK4---libadwaita-issues . I don't think you should hurry either. There are several minor issues that become annoying very quickly.

If you are in a hurry and if it works for you, using https://github.com/dialect-app/py-googletrans might be better for now. In the worst case scenario, all you'll have to do is some patching on Dialect as well.

> Also, the PR seems to have got rid of py-googletrans, could the README.md reflect this?

Oops, missed that, thanks for pointing out.

**Comment by fushinari** [comment]
> I've updated the dialect-git AUR package, it's working again. Thanks @fushinari! +1

Glad to know! :smile:

**Comment by LyesSaadi** [comment]
Ok, thank you for that answer ! I'll try things on my side to solve this :smile: !

Probably either replacing py-googletrans with yours, or patching the old release to use the new backend if possible.

**Comment by fushinari** [comment]
> Probably either replacing py-googletrans with yours

This would be the easier way.

> , or patching the old release to use the new backend if possible.

If you do want to do this (I genuinely don't recommend it), https://github.com/dialect-app/dialect/blob/c974e15b1505f854164f553903ae855e7c54f588/dialect/translators/libretrans.py is kind of good reference for libsoup

**Comment by LyesSaadi** [comment]
Hey :wave: !

After some consideration, I'll just apply https://github.com/ssut/py-googletrans/pull/291 ! I made sure it works (didn't have any network error on my side), and made sure the patch made sense by looking into both httpcore and httpx.

I didn't end up replacing py-googletrans with yours since it would be quite troublesome to change the canonical source of a package, and, I'll be abandoning it as soon as the next dialect update is here anyway.

**Comment by LyesSaadi** [comment]
Um, I'm also now having Network Errors on my side. But, I think that is then just unrelated to the patch.

**Comment by LyesSaadi** [comment]
Yeah, I can confirm that is the case, since the non-legacy `translate()` continues to work (while it didn't without the patch). So, it's just Google blocking the requests!

**Comment by fushinari** [comment]
> Um, I'm also now having Network Errors on my side. But, I think that is then just unrelated to the patch.

Yeah it's because it's using the legacy api I think. Not much any of us can do about it. We're also not in a position to be able to ship the next version asap either unfortunately.
