### ISSUE TITLE
Use lingva-translate as backend

### ISSUE THREAD

**Issue by carallo** [dialect-app/dialect#238]
Hi! First of all thanks for developing this app.

I lately found out about [lingva-translate](https://github.com/TheDavidDelta/lingva-translate), which is a GTranslate scraper similar to invidious, NewPipe, nitter, etc...
Could it be a good idea to implement it as a backend for Google Translate?

**Comment by fushinari** [comment]
I agree. Lingva is very interesting, we'll have to look into it more closely. It also has TTS support, so that's especially interesting.

**Comment by carallo** [comment]
Amazing! Looking forward to try it!
