### ISSUE TITLE
Slow performances at startup

### ISSUE THREAD

**Issue by azmeuk** [dialect-app/dialect#254]
I just tested dialect 1.4.1 on a Librem5 and the UI fits very well the mobile screen. Congratulations.

However, the application is quite low to start, like 6s or 7s.
It is long enough than I wondered if it had crashed. This happens every time.

**Comment by azmeuk** [comment]
Just tested with 2.0.2 on a Librem5. Now it takes 4s to open.

**Comment by rafaelmardojai** [comment]
@azmeuk Could you install [Blanket](https://flathub.org/apps/details/com.rafaelmardojai.Blanket) and see if it has the same startup performance? 

If so, it is probably a python thing.

**Comment by azmeuk** [comment]
Indeed Blanket also takes 4s to open on a L5.

**Comment by ix5** [comment]
Adding a data point, it takes about 3.5 seconds (timed with stopwatch) to run the flatpak version (2.1.1) as of 2023-03-11 via `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=dialect app.drey.Dialect`

The flatpak version of [Blanket](https://flathub.org/apps/details/com.rafaelmardojai.Blanket) opens nearly instantaneously for me.

My computer has a `Intel(R) Core i7-8550U CPU` and runs on a very fast SSD.

**Comment by mufeedali** [comment]
@ix5 That should be flatpak as you guessed. It's probably loading all the runtimes for the first time. Load time after a fresh boot for all GNOME Flatpak apps should be the same.

**Comment by mufeedali** [comment]
Closing as there's nothing to be done from our end
