### ISSUE TITLE
App too wide on Mobile

### ISSUE THREAD

**Issue by baarkerlounger** [dialect-app/dialect#262]
On mobile devices in portrait mode the default translate view is too wide to be useable since the GTK4 port. Perhaps this could be fixed by having the text panes switch from side by side to one below the other when the screen width is below a certain minimum?

**Comment by fushinari** [comment]
It's already supposed to be doing that. Can you tell me the width of your display in pixels?

**Comment by baarkerlounger** [comment]
720px I believe. It's a PinePhone.

**Comment by fushinari** [comment]
I see. Our ui goes adaptive at 680. I don't remember why that was done though... But i think we need another way to detect mobile mode...

**Comment by baarkerlounger** [comment]
I think the Librem 5 is also 720 and they're the two most common mobile linux devices so maybe makes sense to make that the threshold for now?

**Comment by fushinari** [comment]
Yes, I'll do that when I get home. But we need some other way because it stops being an option if and when 1080p displays become common in the Linux world as well.

**Comment by baarkerlounger** [comment]
I think the px width needs to be considered together with the scaling factor. i.e in this case it's really equivalent to 360px width on a desktop with 100% scaling. Doing it that way 680 would work for 720 or 1080 mobile displays?

**Comment by rafaelmardojai** [comment]
The only correct way of fixing this is by wrapping the cards when they don't fit instead of changing the orientation in a fixed pixels size. So this is blocked by [AdwWrapLayout/Box ](https://gitlab.gnome.org/GNOME/libadwaita/-/merge_requests/219).

**Comment by Exalm** [comment]
That was not a correct fix in the slightest. Instead, it broke it on hidpi desktops.

![Screenshot from 2022-07-17 19-33-35](https://user-images.githubusercontent.com/1510457/179405608-c5d81a5a-ee7f-4161-a3d1-471b9b420079.png)

The real issue is that you use `GtkWindow:default-width/height`. If the window is maximized (like it is on mobile), they are the size the window will be when unmaximized. _Not_ the current size. That's why they are called *default* size.

**Comment by fushinari** [comment]
Then how do we get the current size?

**Comment by Exalm** [comment]
Generally speaking, you don't. You use widgets like `GtkFlowBox` to reflow your content automatically - which it does as part of its allocation based on its own size. Listening to window size and changing layouts is, overall, undefined behavior.

Don't forget to:
1. Set focusable=false on flowbox children
2. selection-mode=none
3. Style the children to remove their padding

I do want to do that in a robust way in future (and have a prototype actually), but for now just don't do that.

If you still want to do it without a flowbox or similar widget - override size_allocate() and do it there before chaining up. You will get criticals and flicker though, but that's unavoidable here.

**Comment by rafaelmardojai** [comment]
@Exalm In GTK3 we listened to `check-resize` and used `get_size()`, so this was a lazy port of that. We knew that this was  undefined behavior but was the easy path without using squeezer or flowbox.

And yes, looks like we totally miss understood how scale factor works.

**Comment by Exalm** [comment]
Well, in GTK3 it wasn't correct either. :) This particular issue didn't happen though because _that_ size was current size.

**Comment by rafaelmardojai** [comment]
> Well, in GTK3 it wasn't correct either.

Again, we knew that.

**Comment by azmeuk** [comment]
For the record, here is how 2.0.1 looks on a Librem5

![2022-07-17-182349](https://user-images.githubusercontent.com/60163/179411568-492dda72-0e89-498d-a4ec-1d1f6bc1b740.png)

**Comment by azmeuk** [comment]
@rafaelmardojai it is better with 2.0.2, but still a tiny bit too large
![2022-07-18-201840](https://user-images.githubusercontent.com/60163/179576762-a0cd897a-e252-49e0-bd04-d7c27c627adc.png)
