### ISSUE TITLE
.deb format 

### ISSUE THREAD

**Issue by dtantono** [dialect-app/dialect#266]
Hi
I think this app will be great if we have deb format. Is this possible?

**Comment by rafaelmardojai** [comment]
Sadly we don't have time to maintain packaging other then Flatpak, but contributions are welcome.

Also non of us use a Debian based system, and neither have experience with .deb packaging.

**Comment by stinerman** [comment]
Sorry to necro this, but for anyone wondering, Dialect is available in Debian.

**Comment by mufeedali** [comment]
No worries. Guess we can close this now :)
