### ISSUE TITLE
Translate the selected text

### ISSUE THREAD

**Issue by linsui** [dialect-app/dialect#272]
Crow Translate provide a [D-Bus API](https://github.com/crow-translate/crow-translate#d-bus-api) so that I can select some text and translate it with a shortcut. I can use the command line interface of dialect but it does not bring dialect to foreground. Is there a similiar function in dialect? Thanks!

**Comment by rafaelmardojai** [comment]
Duplicated of #207.

**Comment by rafaelmardojai** [comment]
> I can use the command line interface of dialect but it does not bring dialect to foreground.

About this, running Dialect with it's command line parameters should launch the app. So if this is not happening please report another bug with this info.
