### ISSUE TITLE
default LibreTranslate pussthecat instance offline

### ISSUE THREAD

**Issue by camelCaseNick** [dialect-app/dialect#273]
The default LibreTranslate instance currently is [libretranslate.pussthecat.org](https://libretranslate.pussthecat.org/). It shut down.

https://github.com/dialect-app/dialect/blob/2e686c6da026baac9a210aabc038fad903c71912/dialect/translators/libretrans.py#L32

Alternatives: Currently, I get responses without an API key from libretranslate.de, though I cannot find ToS anywhere. I don't know of any other open (as in, no API key needed) endpoint.

**Comment by fushinari** [comment]
Yeah, we might have to default to libretranslate.de . If that gets shut down within two months, we're definitely defaulting to no instance by default.

@rafaelmardojai Does that sound good?
