### ISSUE TITLE
Copy-pasting bugs using keyboard shortcuts

### ISSUE THREAD

**Issue by resiehnnes** [dialect-app/dialect#275]
After recent updates there are bugs when doing some copy-pasting using keyboard shortcuts.

1. If there is a text in left section which you want to replace by one which is in your clipboard doing 'ctrl+a' -> 'ctrl+v' does not replace it but instead adds to the end of your old text.
2. Same goes if I want to copy selected text in left section, doing 'ctrl+a' -> 'ctrl+c' does not copy selected text but copies the one in the right section (translated one)

Fedora 36, X11, Dialect 2.0.2

**Comment by rafaelmardojai** [comment]
I can't reproduce this in Wayland. Will try later in X11, but I'm guessing a GTK4 bug with X11.

**Comment by resiehnnes** [comment]
Can confirm that everything works well on Wayland

**Comment by fushinari** [comment]
Yeah... in general, GTK4 + X11 is currently a bad combo. I don't think they have the manpower to fix it either. We hit these kinds of weird issues during our development too.

Even GTK4 + Plasma Wayland is still overall not a great experience. For normal users, it should be fine. But the whole portal situation is kinda broken, with it being unclear if or not we have to install "xdg-desktop-portal-gtk". Also, even with all dependencies, any application you run through GNOME Builder will still have broken icons, a broken cursor, broken font rendering and more.

It was also part of why development of the GTK4 port was so slow. As a Plasma user for the most part, it wasn't a great experience working with it. I ended up whining about it a lot to Rafael 😅
