### ISSUE TITLE
Dark theme bugged

### ISSUE THREAD

**Issue by breatfr** [dialect-app/dialect#276]
hi, i use sometimes dialect in dark theme on linux mint 21 from flathub with lingva.ml translator for some words i don't know, that works great.
but when i write something in this app, that is in black and black on grey I see nothing 🙂
I need put light theme and dark theme again to fix it. isn't hard but each time it's annoying.
i searched in /home/breat/.var/app/app.drey.Dialect/config to try to find somethings to fix it but without success.
someone can help me  ?

**Comment by fushinari** [comment]
Are you using any themes?

**Comment by breatfr** [comment]
no the Mint-Y dark include in mint 21

**Comment by fushinari** [comment]
Yeah, we can't support anything other than Adwaita from our side. Anything other than that is out of our control. Request a fix from the theme developers.
