### ISSUE TITLE
Provide offline translations utilizing Mozillas translation mechanism?

### ISSUE THREAD

**Issue by stefan-niedermann** [dialect-app/dialect#277]
A complete offline working app has several advantages

- Huge privacy improvements
- Not depending on 3rd party servers which might or might not be availabke
- Network not required (traveling via train or so)
- Saving metered data volume
- ...

Mozilla allows to translate websites completely offline / local within the Firefox browser utilizing the `Bergamot` project. Maybe this can be adapted as an additional option?

https://browser.mt/software

**Comment by fushinari** [comment]
Duplicate of #183

**Comment by stefan-niedermann** [comment]
Oof, how could i miss that? 🙈 sorry for the noise!

**Comment by fushinari** [comment]
No worries. :)
