### ISSUE TITLE
There are no spaces between sentences in translation

### ISSUE THREAD

**Issue by SokolovskyMaxim** [dialect-app/dialect#296]
When I translate several sentences, there are no spaces between the sentences as a result of the translation. It looks destructive. In the screenshot you can see how it is displayed

**Comment by SokolovskyMaxim** [comment]
https://wampi.ru/image/R2rk58k

**Comment by rafaelmardojai** [comment]
Could you give us info about the provider you're using? Google?

**Comment by SokolovskyMaxim** [comment]
Yes, I use Google provider
