### ISSUE TITLE
Feature Request: Allow usage of self-hosted/local LibreTranslate

### ISSUE THREAD

**Issue by Saijin-Naib** [dialect-app/dialect#300]
Currently, I can't point Dialect at a LibreTranslate instance on the same machine (localhost:5000), nor can I point my other machines in my home network to that instance via that machine's hostname/ip/port (greenmachine:5000 or 192.168.1.100:5000).

Would it be possible for Dialect to allow these addresses so I don't need to setup a DNS name, reverse proxy, et al just to use a local/self-hosted LibreTranslate instance within my own home?

**Comment by rafaelmardojai** [comment]
Did you resolve this? Dialect should connect to `localhost` just fine.

**Comment by Saijin-Naib** [comment]
Strong user error 😬

It does indeed work perfectly fine with localhost, I just forgot to adjust UFW rules.
