### ISSUE TITLE
Translation failed

### ISSUE THREAD

**Issue by apple-corps** [dialect-app/dialect#303]
I get this message when trying to translate perhaps too large a block of text. But I am not sure if it's because it's too large a block of text, or some other reason.

Then perhaps provide a way to understand why translation failed?

**Comment by rafaelmardojai** [comment]
If this is related to #304, then probably you're getting a char limit error.

The thing is that it isn't covered by the UI at this stage because it assumes that you should have got an error before sending the request. Could you run the app in the terminal and see what it's printed?

**Comment by apple-corps** [comment]
Let me try this again within a few days.
