### ISSUE TITLE
Not displaying number of characters on initial run

### ISSUE THREAD

**Issue by apple-corps** [dialect-app/dialect#304]
Related to #303 

When I pasted about 35,000 characters in on my first run, it did not show the number of characters. It just displayed 0 / 2000. I hit translate and got #303 . Then it should always display the number of characters input on the left side.

**Comment by rafaelmardojai** [comment]
Hmm, did you use the paste button right? 

Seems that when we are manually setting the clipboard text to the entry we aren't getting the changed signal that has to update the chars counter.
