### ISSUE TITLE
Question mark seems to cut the translation

### ISSUE THREAD

**Issue by clobrano** [dialect-app/dialect#308]
It seems that using a question mark either cut the message sent to translation, or the translation replies. Either way, everything that goes after the question mark is not translated.

I am using Lingva translate, with Google translate it does not occur

Without question mark
![image](https://user-images.githubusercontent.com/2883614/218070994-1807e6b5-6a85-4edd-8e46-8d31e4c4acd9.png)

With question mark
![image](https://user-images.githubusercontent.com/2883614/218071052-a372f590-2c3a-4aec-b345-5e0654449c83.png)

**Comment by rafaelmardojai** [comment]
This is using the Google backend right?

**Comment by clobrano** [comment]
> I am using Lingva translate, with Google translate it does not occur

no, the other way around. Google backend works fine, the error is with Lingva
