### ISSUE TITLE
[Update] Gnome 44 Runtime

### ISSUE THREAD

**Issue by BirdInFire** [dialect-app/dialect#320]
Since all dev have a life i let you know that gnome 44 runtime is out on flathub :+1:

**Comment by rafaelmardojai** [comment]
Yes, I'm aware of that. We will probably wait a bit and try to do a release soon and update both the app and the runtime.

If that doesn't happen in a month or so, I'll just update the runtime.

**Comment by julianfairfax** [comment]
> Yes, I'm aware of that. We will probably wait a bit and try to do a release soon and update both the app and the runtime.
> 
> If that doesn't happen in a month or so, I'll just update the runtime.

It's been half a year, so I assume no release is happening. It would probably be a good idea to update the runtime now, because:

> The GNOME 43 runtime is no longer supported as of September 20, 2023. Please ask your application developer to migrate to a supported platform.

**Comment by rafaelmardojai** [comment]
Yeah true. I definitely want to release Dialect 2.2 this weekend for GNOME 45. But would be fine to update the manifest to 44 first.
