### ISSUE TITLE
Building with Meson fails due to missing source file

### ISSUE THREAD

**Issue by somepaulo** [dialect-app/dialect#323]
Following the instructions for building with Meson/ Ninja I get the following error:

```sh
[34/49] Generating data/resources/dialect_gresource with a custom command
FAILED: data/resources/dialect.gresource 
/usr/bin/glib-compile-resources ../dialect/data/resources/dialect.gresource.xml --sourcedir data/resources --sourcedir ../dialect/data/resources --internal --generate --target data/resources/dialect.gresource --dependency-file data/resources/dialect.gresource.d
../dialect/data/resources/dialect.gresource.xml: Failed to locate “shortcuts.ui” in any source directory.
```

Browsing the source code I couldn't find this file anywhere.
Am I missing something?

**Comment by rafaelmardojai** [comment]
You need `blueprint-compiler` to compile the `.blp` files to `.ui`. Looks like it was left out from the README.

Also it's strange that meson isn't complaining about that. We probably need to improve that.

**Comment by somepaulo** [comment]
I have `blueprint-compiler` installed.
I've tried installing `dialect` from the AUR, which pulls it as a dependency, but I'm getting the same error about missing `.ui` files.
Is it my `meson` misbehaving?

**Comment by somepaulo** [comment]
The issue seems to be with the 'blueprint-compiler`.
It prints out a generic help message when run:

```
[43/49] Generating data/resources/blueprints with a custom command
usage: blueprint-compiler [-h] [--version] command ...

positional arguments:
  command
    compile      Compile blueprint files
    batch-compile
                 Compile many blueprint files at once
    port         Interactive porting tool
    lsp          Run the language server (for internal use by IDEs)
    help         Show this message

optional arguments:
  -h, --help     show this help message and exit
  --version      show program's version number and exit
[49/49] Generating data/resources/dialect_gresource with a custom command
FAILED: data/resources/dialect.gresource 
/usr/bin/glib-compile-resources ../dialect/data/resources/dialect.gresource.xml --sourcedir data/resources --sourcedir ../dialect/data/resources --internal --generate --target data/resources/dialect.gresource --dependency-file data/resources/dialect.gresource.d
../dialect/data/resources/dialect.gresource.xml: Failed to locate “shortcuts.ui” in any source directory.
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
````

I've looked up the command in `compile_commands.json` and ran it.
I get the same output:

```
/usr/bin/blueprint-compiler batch-compile data/resources/. ../dialect/data/resources ../dialect/data/resources/theme-switcher.blp ../dialect/data/resources/lang-selector.blp ../dialect/data/resources/window.blp ../dialect/data/resources/lang-row.blp ../dialect/data/resources/about.blp ../dialect/data/resources/shortcuts.blp
usage: blueprint-compiler [-h] [--version] command ...

positional arguments:
  command
    compile      Compile blueprint files
    batch-compile
                 Compile many blueprint files at once
    port         Interactive porting tool
    lsp          Run the language server (for internal use by IDEs)
    help         Show this message

optional arguments:
  -h, --help     show this help message and exit
  --version      show program's version number and exit

```

It's as if `blueprint-compiler` doesn't understand the command...
Can this be some borked config on my side?

**Comment by rafaelmardojai** [comment]
I don't have the time right now to test on host, but we usually only build with Flatpak and everything works fine.

Also, right now our flatpak manifest uses blueprint `0.4.0` , what version are you using? Although technically it should work fine with `0.6.0`.

**Comment by somepaulo** [comment]
> we usually only build with Flatpak

Yes, that works fine.
But the Meson build from the AUR on Arch used to build and work fine before. I got this issue trying to update. Getting the same with the [Converter](https://gitlab.com/adhami3310/Converter) app. But the dev there isn't replying at all...

> what version are you using?

`0.6.0`

**Comment by somepaulo** [comment]
Nevermind this.
The issue is with `blueprint-compiler` on Arch.
Installing `blueprint-compiler-git` from the AUR solves this issue.
