### ISSUE TITLE
Always running in the background

### ISSUE THREAD

**Issue by Nokse22** [dialect-app/dialect#329]
With the recent introduction of "Backgrond App" in gnome 44 I noticed that Dialect is very often running in the background.

I know it is for Gnome search, but the other apps that I see start in the background when searching something usually are closed within a few seconds, Dialect remains open.

**Comment by not-a-dev-stein** [comment]
Sorry for reviving this thread out of nowhere, but has this really been fixed? Ever since the introduction of Background Apps and until this day I still have Dialect always showing up in it:

![image](https://github.com/user-attachments/assets/b100db1b-2afc-4e60-8464-d126acc5d827)

**Comment by rafaelmardojai** [comment]
Yeah, can reproduce. This probably is a regression from when we changed the SP to be async.
