### ISSUE TITLE
Using dialect in Flatpak does not work with gnome search provider.

### ISSUE THREAD

**Issue by ideveCore** [dialect-app/dialect#338]
The gnome shell search (org.gnome.Shell.Search Provider 2) doesn't work in Flatpak, I tested it with AUR and it worked.

**Comment by rafaelmardojai** [comment]
Is it enabled in GNOME Settings search panel?

**Comment by ideveCore** [comment]
I will install the app on the flatpak again and check

**Comment by ideveCore** [comment]
It's working now, I didn't realize that in flatpak this configuration has to be manual

**Comment by ideveCore** [comment]
You can close this issue, it was just my mistake.

**Comment by rafaelmardojai** [comment]
> It's working now, I didn't realize that in flatpak this configuration has to be manual

Yes, for some reason (security probably) flatpak packages haver the search provider disabled by default.
