### ISSUE TITLE
Inaccurate "network issue" error message for languages that don't support TTS

### ISSUE THREAD

**Issue by yabobay** [dialect-app/dialect#342]
If i try to use TTS for a language that doesn't support it (backend: google translate, i haven't tried the others), instead of showing me that TTS isn't available, it'll give me "A network issue has occurred. Please try again.".

I think instead it should show a more accurate error message, or maybe have the button be greyed out and show a message when hovered.

**Comment by rafaelmardojai** [comment]
Current development branch should have more meaningful error messages in general.

Also in general the TTS action should be disabled if the lang doesn't have TTS support, maybe there's a bug with the current stable version.
