### ISSUE TITLE
Flatpak runtime upgrade from gnome 43 to the latest one?

### ISSUE THREAD

**Issue by Agi0m** [dialect-app/dialect#344]
OS: Linux Mint
Version: 21.2

Hi, Flatpak keeps telling me that the runtime 43 Dialect uses is no longer supported as of September 20. 
Does this impact the usage of the app or I can just keep using it as it is.

**Comment by rafaelmardojai** [comment]
I'm updating it to the 44 runtime (https://github.com/flathub/app.drey.Dialect/pull/6). We'll be releasing a new version along with an update to 45 this week, just fixing some last minute bugs.

**Comment by Agi0m** [comment]
That sounds great. Thanks a lot.
