### ISSUE TITLE
Hide the "Show pronunciation" option if the chosen service does not suport it

### ISSUE THREAD

**Issue by Odi-3** [dialect-app/dialect#371]
Hide the "Show pronunciation" option if the chosen service does not suport it. It would be more consistent if the relevant keyboard shortcut was hidden too.

**Comment by rafaelmardojai** [comment]
It is implemented with actions (`Gio.Action`) and it is not possible to hide actions in the toolkit, only to disable them.

So in order to be implemented we would have to make major changes to how it is triggered and I don't think that's worth it.
