### ISSUE TITLE
Instance URL "lingva.ml" doesn't work anymore

### ISSUE THREAD

**Issue by meybonomme** [dialect-app/dialect#372]
I use Lingva Translate as a provider and since yesterday I got "Translation failed" error. Terminal output is `ERROR:root:'info'`

Webpage https://lingva.ml works perfectly fine.
Lingva Translate works also perfectly fine with Translate You app in my phone: https://github.com/you-apps/TranslateYou
But Translate You is using by default `lingva.lunar.icu` instead of `lingva.ml` as instance.

I've often had "Translation failed" errors with Dialect using the `lingva.ml` as instance, but never with Translate You app, which by default using `lingva.lunar.icu` as instance. I changed manually the instance in Dialect to `lingva.lunar.icu` and now it works perfectly there too.

So I also recommend changing in Dialect the default Lingva Translate instance to `lingva.lunar.icu`.

**Comment by mufeedali** [comment]
From the next release onwards, we will be switching to our own lingva and libretranslate instances, so should be fine :)

**Comment by meybonomme** [comment]
Awesome! Thank you for the reply!
