### ISSUE TITLE
Headerbar expands when Chinese characters are translated

### ISSUE THREAD

**Issue by AbrarSL** [dialect-app/dialect#376]
![image](https://github.com/dialect-app/dialect/assets/69783006/9c151260-32bc-4fd2-8109-358759ff5db1)
This is what it looks like.

You can try it for yourself by trying to translate these characters `非洲小伙好兄弟 唱红歌已无法自拔`

![image](https://github.com/dialect-app/dialect/assets/69783006/9bfd3e2c-77c0-4139-823f-e054f5627318)
It fixes itself once I hit translate on some latin characters.

**Comment by rafaelmardojai** [comment]
I can't reproduce this issue in the latest version.

**Comment by AbrarSL** [comment]
Can confirm that the issue doesn't seem to be present in the latest version
