### ISSUE TITLE
Clear icon is ambiguous

### ISSUE THREAD

**Issue by Melodee618** [dialect-app/dialect#383]
Because the clear icon is stacked, it gives the impression that all the previous translations will be cleared, not just the
current one, making users hesitant to use it.

![Untitled document](https://github.com/dialect-app/dialect/assets/86478882/86f5773a-691c-4f8a-a634-7255ae545323)

I would recommend using a more conventional clear icon.
For instance, a simple 'x', like the one used on Google Translate.

![Screenshot (11)](https://github.com/dialect-app/dialect/assets/86478882/e826b56e-5451-4a48-84f9-a7f1ede05839)

**Comment by rafaelmardojai** [comment]
Right now we use `edit-clear-all-symbolic` from the icon theme.

One option is to use `edit-clear-symbolic`:
![Captura desde 2024-04-11 07-53-10](https://github.com/dialect-app/dialect/assets/6210397/5f9bf4f4-478a-436f-8dc8-75694d197464)

Alternative we can bundle any other icon suitable from the [icon-development-kit](https://gitlab.gnome.org/Teams/Design/icon-development-kit):

 ![Captura desde 2024-04-11 07-58-14](https://github.com/dialect-app/dialect/assets/6210397/1fbd46f1-d35a-46e4-af80-9d9897796fce)
![Captura desde 2024-04-11 07-58-33](https://github.com/dialect-app/dialect/assets/6210397/0ac62893-5eab-444f-9566-a5196fbcb617)

@mufeedali thoughts?

**Comment by mufeedali** [comment]
Let's simply use `edit-clear-symbolic`.  I feel that the icon is universal enough to be well-understood.
