### ISSUE TITLE
Changing font size doesnt work with any font other than cantarell

### ISSUE THREAD

**Issue by notHaider** [dialect-app/dialect#394]
Im on GNOME 46 endavour os (arch) and whenever i change my font with gnome-tweaks to something other than cantarell i lose the functionality to increase and decerase the font size.

You can bypass this issue by first having the font as cantarell then opening dialect and tehn changing the font size in this situation you can change the font size normally

**Comment by mufeedali** [comment]
@notHaider Can you let us know the font you were testing with?

**Comment by notHaider** [comment]
ubuntu nerd and inter variable

**Comment by notHaider** [comment]
i used ubuntu nerd and inter variable i just noticed that inter normal works tho

**Comment by rafaelmardojai** [comment]
@notHaider Could you try our latest flatpak nightly build (you can get it from our website  https://dialectapp.org) or `dialect-git` from AUR? I would like to know if 3c0957950ed0efa07a2fd429dedbc1aa77b808cb commit solves the issue.

**Comment by notHaider** [comment]
i tried the nightly flatpak and it works perfectly fine there. probably should have tried that first 🤦‍♂️.

**Comment by rafaelmardojai** [comment]
@notHaider Thanks for confirming! We'll try to make bug release soon.
