### ISSUE TITLE
Update language list for Google Translate

### ISSUE THREAD

**Issue by Mejans** [dialect-app/dialect#402]
Hello!
Google Translate now supports even more languages.
For instance, Occitan and Kabyle, are not handled.
Would it be possible to update the language list in the dialect application?
Best regards

**Comment by rafaelmardojai** [comment]
We probably want to dynamically collect languages on init like we do for Bing, so we don't have to maintain a list of languages.

**Comment by Mejans** [comment]
Alright :)
