### ISSUE TITLE
Translate from primary selection not work

### ISSUE THREAD

**Issue by FusionGold** [dialect-app/dialect#407]
I am encountering an issue with `Dialect`, both when installed via AUR (dialect-git) and Flatpak on my Archlinux Gnome Wayland desktop environment. When running `dialect -n` from terminal and attempting to translate from the primary selection, the following error occurs:
```
Traceback (most recent call last):
  File "/app/share/dialect/dialect/window.py", line 532, in on_paste
    text = clipboard.read_text_finish(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-io-error-quark: Cannot read from empty clipboard. (1)
``` 

Steps to Reproduce:
1. Install Dialect via AUR (dialect-git) or Flatpak.
2. In GNOME Text Editor, select a word and ensure `wl-paste --primary` can paste the content.
3. With the flatpak version, run `LANG=C flatpak run app.drey.Dialect -n`
4. `Dialect` window poped up with empty input and the above error message.

**Comment by ivan-toriya** [comment]
Experiencing the same issue. Dialect 2.5.0, installed via flatpak.

**Comment by ivan-toriya** [comment]
Working fine after I enabled `Socket` > `D-Bus system bus` for Dialect via Flatseal

**Comment by ivan-toriya** [comment]
Identified another issue: clipboard history is only available for running apps.
So, in order to translate the selection, I just run the `flatpak run app.drey.Dialect --selection` twice via custom shortcut.

**Comment by rafaelmardojai** [comment]
If you use the paste button in Dialect, do you get the same error?

**Comment by FusionGold** [comment]
Paste button works fine if I have contents in my clipboard.

**Comment by rafaelmardojai** [comment]
Right, @mufeedali confirmed me that he could reproduce the problem, but I can't in my Fedora setup.

@ivan-toriya could you give me info about your system? I can get the selection activating Dialect once.

**Comment by ivan-toriya** [comment]
@rafaelmardojai 
Debian 12.7, Gnome 43.9 (Wayland)

**Comment by ivan-toriya** [comment]
@rafaelmardojai 
btw, is it possible to run Dialect in background or in minimized mode?

**Comment by rafaelmardojai** [comment]
@ivan-toriya Nope.

**Comment by FusionGold** [comment]
@rafaelmardojai Thanks for the workaround hint.

**Comment by zefr0x** [comment]
> Identified another issue: clipboard history is only available for running apps. So, in order to translate the selection, I just run the `flatpak run app.drey.Dialect --selection` twice via custom shortcut.

You need to focus on Dialect window before the second run.

It might be a Wayland thing that prevents a window from reading the clipboard unless you are currently focusing on it.

@rafaelmardojai can we wait for the user to focus on the window before reading the clipboard?

**Comment by rafaelmardojai** [comment]
@zefr0x Yes that's possible.

Implemented that in #408, could you test that PR?

**Comment by FusionGold** [comment]
@rafaelmardojai It seems that the primary selection can be correctly filled in with #408 . However, now whenever the `-n` option is used, a 'Translation failed' warning pops up first, and then the translation appears.
![Screenshot from 2024-11-02 01-46-24](https://github.com/user-attachments/assets/8602dde2-782a-4151-b57d-0278d48ea79d)

**Comment by rafaelmardojai** [comment]
@FusionGold should be fixed now, could you test?

**Comment by FusionGold** [comment]
@rafaelmardojai Everything seems fine for me. Thanks for your hard work!
