### ISSUE TITLE
Available services should be limited by enabled web accounts in Settings

### ISSUE THREAD

**Issue by jeblad** [dialect-app/dialect#414]
Because translation services leaks information they should be limited by whatever web accounts are enabled in the Settings app. The Dialect app may configure the actual parsing, but allowing the external service should be trough Settings.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the Dialect app to use GNOME Online Accounts (GOA) for authorizing translation services. This change ensures that only web accounts enabled in the GNOME Settings app are used for translations, addressing privacy concerns about information leakage.

You can review changes in this commit: https://github.com/mnmnk43434/dialect-app-dialect-414/commit/02e9c6fb32ccc0fcc00633372e793bf75f1a12b7.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by rafaelmardojai** [comment]
I don't understand how web accounts in Settings can relate to translation services? We don't need any auth from them and also they serve for a totally different purpose (mail, calendar, files).

Right now all Dialect providers are online, so yeah, it "leaks" (sends) data to the service server, but only will do with the enabled Translation and TTS provider.

**Comment by jeblad** [comment]
What you _need_ and what you should _do_ isn't always the same. You should provide the user with sufficient information about the machine and its complete operating environment to make a deliberate choice. If some program bypasses the mechanisms for securing the machine it is bad.

All applications that sends out information to external service providers (data confidentiality) or changes information based upon response from external service providers (data integrity) should go through the provided security mechanisms, and the provided security mechanisms should do deep inspections as necessary.

This is an error with several applications and packages in the GNOME system.

**Comment by rafaelmardojai** [comment]
So you want us to add a Google, DeepL, Yandex, etc entries in GNOME Online Accounts (I really doubt they would accept such addition honestly) and do what from there? GOA is intended for granting auth in an unified place, and we don't need any auth at all.

**Comment by mufeedali** [comment]
To add to what Rafael has already said here, GOA isn't intended as a security mechanism at all. So using it as one would be weird.

Dialect is an online translation app right now. Installing it comes with the expectation that data is sent to an external server to translate. You can use our own LibreTranslate instance (lt.dialectapp.org) if you're worried about service providers snooping. As you can guess, we have no interest in what you translate.

As an offline alternative, you could use Dialect with a local instance of LibreTranslate and if you set it once, it won't send data to any external servers anymore.

Proper offline provider support is also planned as you can see from the issue tracker.
