### ISSUE TITLE
Add DeepL backend

### ISSUE THREAD

**Issue by ai** [dialect-app/dialect#47]
[DeepL](https://www.deepl.com/translator) is insane good in translation quality (much better than Google Translate for many language pairs). Seems like they have [API](https://www.deepl.com/en/docs-api/).

It will be nice to have a setting to switch between Google Translate and DeepL backends.

**Comment by rafaelmardojai** [comment]
To my knowledge you need to pay to have access to the API. You also need a secret KEY to authenticate.

So, If I'm not wrong, we will need a subscription to develop this request. And users aiming to use DeepL, will need to provide their own API KEY.

**Comment by ai** [comment]
Sad.

Good thing, that the basic API key is [free](https://www.deepl.com/en/pro#single).

**Comment by fushinari** [comment]
> Good thing, that the basic API key is [free](https://www.deepl.com/en/pro#single).

No, API access is fully paid sadly.

**Comment by sp1ritCS** [comment]
Too bad that they dont use static pages :)

Request:
```sh
curl 'https://www2.deepl.com/jsonrpc' -H 'Content-type: application/json' --data-raw '{"jsonrpc":"2.0","method": "LMT_handle_jobs","params":{"jobs":[{"kind":"default","raw_en_sentence":"Hello World","raw_en_context_before":[],"raw_en_context_after":[],"preferred_num_beams":4,"quality":"fast"}],"lang":{"source_lang_user_selected":"auto","target_lang":"DE"},"priority":-1,"commonJobParams":{},"timestamp":1602790014301}}'
```
Response:
```
{"jsonrpc":"2.0","result":{"translations":[{"beams":[{"postprocessed_sentence":"Hallo Welt","num_symbols":5,"score":-4997.138279201713,"totalLogProb":5.708958496400825},{"postprocessed_sentence":"Hallo Welt!","num_symbols":6,"score":-4998.529303924396,"totalLogProb":2.932460362221432},{"postprocessed_sentence":"Hallo Welt.","num_symbols":6,"score":-4998.548608063369,"totalLogProb":2.893969321615728},{"postprocessed_sentence":"Hallo, Welt","num_symbols":6,"score":-4998.693697186523,"totalLogProb":2.6046722263858275}],"quality":"normal"}],"target_lang":"DE","source_lang":"IT","source_lang_is_confident":false,"timestamp":1602790398,"date":"20201015"}}
```

If It's ethical / legal to this is up to you / your government.

**Comment by fushinari** [comment]
> If It's ethical / legal to this is up to you / your government.

Well... Google Translate is already a gray area really... So yeah maybe we could do this.

**Comment by baarkerlounger** [comment]
PureMaps takes a similar approach where multiple data sources can be used (user configurable) and users can provide their own API keys for different services.

**Comment by fushinari** [comment]
> PureMaps takes a similar approach where multiple data sources can be used (user configurable) and users can provide their own API keys for different services.

Sadly, I can't pay for an API key for now, so I won't be able to test it and I don't want to try and maintain something I can't test. Plus, I personally have a little reluctance to support a feature that will not be accessible to most people. (If we use a "you can give your own API key" approach, only users with a key will be able to use the DeepL backend after all.)

That said, I was more interested in the approach demoed by @sp1ritCS . As for legality... idk. So, if anyone has any idea if that's ok to do, please do tell me.

**Comment by fushinari** [comment]
@rafaelmardojai which approach do you think we should take if we do implement this?

**Comment by rafaelmardojai** [comment]
I will be fine implementing the approach demoed by @sp1ritCS, since [py-googletrans](https://github.com/ssut/py-googletrans) has similar approach.

About adding support for the paid API, I'm fine if someone shows up to implement/maintain it. Since I'm not going to use it, I lack motivation.

**Comment by okias** [comment]
IMHO having multiple backends would be nice! At some point it could be even some Free alternative to these services 😉

**Comment by fushinari** [comment]
> IMHO having multiple backends would be nice! At some point it could be even some Free alternative to these services

Yes, I like the idea too. I just haven't had the time to begin working on it. It's not even difficult really. Just haven't had enough time is all. I'll get around to it next weekend probably.

**Comment by rafaelmardojai** [comment]
> Yes, I like the idea too. I just haven't had the time to begin working on it. It's not even difficult really. Just haven't had enough time is all. I'll get around to it next weekend probably.

I has been thinking about it too. We should write some kind of translation "middleware" that will talk to the different backends based on the preference.

What I don't know is how to handle the recent langs. An option is to have a list per backend but I'm not sure about it.

**Comment by fushinari** [comment]
Yeah, language lists, history, etc will have to be per-backend. In the case of history, we can simply clear it each time the backend is switched though. Some refactoring was needed for the translation bit anyway, so it will be a needed cleanup.

I'm also looking into more solid options. We're in a really troublesome position as it is right now. We're already using an unofficial API over its official counterpart and DeepL's first form of implementation will also probably be its undocumented jsonrpc interface. The issue might be pretty obvious from that: we don't have a reliable free API to count on. We need at least one service where we don't expect the user to give an API key and it just works and is fully free.

I personally am not fan of user-supplied API keys anyway. It will make each and every one of the users' translations personally identifiable. At that point, using the web UI is probably better for privacy.

All that said, I'm not expecting a properly free alternative to be coming in the near future. Apertium is kind of just "existing" and isn't good enough yet. We can use these unofficial or undocumented methods until they run out, but it would be cool if someone could find a decent translation service that we could integrate without any worries like with DeepL or Google.

**Comment by rugk** [comment]
As fir the API key, did you consider just nicely asking DeepL to provide you with a free (maybe limited [per IP?]) API key?
This would be the most legal thing to do this.

Maybe you need to add some logo or sponsoring or write a blog post, but I guess this is all fine, if you get an API key for duno 50 requests / IP or so. :thinking:

**Comment by rafaelmardojai** [comment]
> As fir the API key, did you consider just nicely asking DeepL to provide you with a free (maybe limited [per IP?]) API key?
This would be the most legal thing to do this.

Yeah, I have also thought about that, and that's one of the reasons I haven't started working on this.

We will try to contact **DeepL GmbH** soon.

**Comment by baarkerlounger** [comment]
@rafaelmardojai did you contact DeepL/get any response from them?

**Comment by fushinari** [comment]
Just letting you all know, I did implement the JSONRPC interface at one point but it responds with `429 Too many requests` way too much to be usable. I could still add it in as a backend pretty easily, since we have the framework ready, but it wouldn't work most times.

Regarding contacting DeepL, we've tried, but haven't had any meaningful responses except bot replies and stuff. We'll be trying again soon though. :)

**Comment by GRFreire** [comment]
Hey, I think DeepL has updated their plans, because now they have a Free Plan with "500,000 character limit / month". I believe it is good enough for testing and developing.

Haven't tried it though, so I am not sure.

**Comment by rafaelmardojai** [comment]
> Hey, I think DeepL has updated their plans, because now they have a Free Plan with "500,000 character limit / month". I believe >it is good enough for testing and developing.
>
> Haven't tried it though, so I am not sure.

Nice! 

We're working on API keys support (initially motivated for LibreTranslate), so after that we will be implementing DeepL support.

**Comment by rafaelmardojai** [comment]
So we can't get an API key to develop the DeepL support.

The DeepL API is only available for Europe, USA, Canada and Japan. I guess we could get an API key from someone in the community, but the fact that the service have those limits kinda discourages me.

**Comment by rugk** [comment]
Wait why? Because you are outside of those territories? And even if so, a VPN would likely solve that problem.

**Comment by rafaelmardojai** [comment]
> Wait why? Because you are outside of those territories? And even if so, a VPN would likely solve that problem.

Yeah. It requires a credit card from one of those countries

**Comment by rugk** [comment]
Ah well then likely banking/payment processor regulatioms/restrictions.

**Comment by rafaelmardojai** [comment]
Yeah, seems like they're using Stripe.

**Comment by rafaelmardojai** [comment]
> > Ah well then likely banking/payment processor regulatioms/restrictions.
> 
> Yeah, seems like they're using Stripe.
> 
> Edit: But I through that the Stripe restrictions were for selling, not paying.

Hmm, actually DeepL don't accept countries that are allowed on Stripe, so I guess it's their decision.

**Comment by wineTGH** [comment]
What about this unofficial [implementation](https://github.com/ptrstn/deepl-translate)?

**Comment by bkis** [comment]
> What about this unofficial [implementation](https://github.com/ptrstn/deepl-translate)?

Might be something. The only problems I see:

1. Is this lib well maintained enough to keep up with changes on how DeepL renders their website (I suppose it's scraping the results from there and doesn't use the API)?
2. Is the limit of 5000 chars per translation when using the web translator a problem (I guess no)?

**Comment by Nekothegamer** [comment]
just found on the [DeepL api page](https://www.deepl.com/pro-api) and i saw that the api is actually free to use, since the free version gives you full access to the rest api

**Comment by rafaelmardojai** [comment]
@Nekothegamer, yes we know about the free API for a long time, but today decided to check and discovered that it is finally available for our countries (Dialect developers), so next version of Dialect will have a translation provider for the official DeepL API.

**Comment by Nekothegamer** [comment]
Nice!, that's amazing!

**Comment by mufeedali** [comment]
DeepL support has been merged and will arrive in the next release :)

**Comment by Nekothegamer** [comment]
Amazing!!!!!! Thank you for your considering <)
